// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

Future<void> initializeFirebase() async{
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3p6r54qBQlxiRYtovgzXrheYt_KmXCQ',
    appId: '1:286934147858:web:5357aae95e7b84216649cb',
    messagingSenderId: '286934147858',
    projectId: 'maps-flutter-492b7',
    authDomain: 'maps-flutter-492b7.firebaseapp.com',
    storageBucket: 'maps-flutter-492b7.appspot.com',
    measurementId: 'G-02KS51NF2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUSHpa9hYLODsGn5hllwF_DhkOsmKmMTg',
    appId: '1:286934147858:android:e2c284ac3b2c8bfb6649cb',
    messagingSenderId: '286934147858',
    projectId: 'maps-flutter-492b7',
    storageBucket: 'maps-flutter-492b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1kHIiSLvCdQYAuZPuS-lICs8mxSuyKBE',
    appId: '1:286934147858:ios:96b569d47eab1d326649cb',
    messagingSenderId: '286934147858',
    projectId: 'maps-flutter-492b7',
    storageBucket: 'maps-flutter-492b7.appspot.com',
    iosBundleId: 'com.example.mapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1kHIiSLvCdQYAuZPuS-lICs8mxSuyKBE',
    appId: '1:286934147858:ios:96b569d47eab1d326649cb',
    messagingSenderId: '286934147858',
    projectId: 'maps-flutter-492b7',
    storageBucket: 'maps-flutter-492b7.appspot.com',
    iosBundleId: 'com.example.mapFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3p6r54qBQlxiRYtovgzXrheYt_KmXCQ',
    appId: '1:286934147858:web:5ee047722e83a4b66649cb',
    messagingSenderId: '286934147858',
    projectId: 'maps-flutter-492b7',
    authDomain: 'maps-flutter-492b7.firebaseapp.com',
    storageBucket: 'maps-flutter-492b7.appspot.com',
    measurementId: 'G-HC2F6Y71MP',
  );
}
